name = "DynamicsVisualisationJulia"
uuid = "2e8eecef-c66c-43e9-b5af-f9c774429c9f"
authors = ["Kiba Mangandango <okami4d@gmail.com>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
Colors = "0.13.1"
GLMakie = "0.13.6"
